package com.gbksoft.neighbourhood.utils.validation

enum class ValidationField(val attrSpecName: String) {
    FULL_NAME("Full Name"),
    EMAIL("Email"),
    PASSWORD("Password"),
    CURRENT_PASSWORD("Current Password"),
    NEW_PASSWORD("New Password"),
    CREATE_PASSWORD("Create Password"),
    CONFIRM_PASSWORD("Confirm Password"),
    CONFIRM_NEW_PASSWORD("Confirm New Password"),
    TERMS("\"Terms & Conditions\" and \"Privacy Policy\""),
    ADDRESS("Address"),
    MY_INTERESTS("My Interests"),
    DATE_OF_BIRTH("Date of Birth"),
    CATEGORY("%s Category"),
    NAME("%s Name"),
    DESCRIPTION("%s Description"),
    PRICE("Price"),
    START_DATE_TIME("Start Date & Time"),
    END_DATE_TIME("End Date & Time"),
    NEW_EMAIL("New Email"),
    AVATAR("Avatar"),
    BUSINESS_NAME("Name of Business"),
    BUSINESS_DESCRIPTION("Business Description"),
    BUSINESS_ADDRESS("Business Address"),
    BUSINESS_SITE("Business Web site"),
    BUSINESS_EMAIL("Business Email"),
    BUSINESS_PHONE("Business Phone"),
    BUSINESS_AVATAR("Business Avatar"),
    VISIBILITY_RADIUS("Visibility Radius"),
    BUSINESS_CATEGORY("Business Category"),
    POST_VIDEO("Post Video"),
    ATTACHMENT_FILE("Attachment File"),
    POST_MESSAGE("Post Message"),
    PRIVATE_MESSAGE("Private Message"),
    STORY_DESCRIPTION("Story Description"),
    STORY_ADDRESS("Story Address"),
    AUDIO_DESCRIPTION("Track Description"),
    AUDIO_DURATION("Track Duration")
}